#!/usr/bin/env python3
# Generate offline-tts-zerotts-abbreviations-table.h from
# scripts/zerotts/data/abbreviations.txt.
#
# abbreviations.txt (adapted from soe-vinorm, MIT -- see
# scripts/zerotts/data/LICENSE.soe-vinorm) is "ABBR:reading[,reading...]" per
# line, with BOTH the uppercase and lowercase spelling of each acronym as
# separate keys. vi_normalizer.py's own docstring is explicit that "only the
# uppercase ones are ever used" (a lowercase dictionary key like "ca" or "tư"
# is an ordinary Vietnamese word far more often than an acronym) -- so this
# generator keeps only the uppercase-keyed entries, roughly halving the
# table for no behavior change versus the Python reference.
#
# Usage:  python3 generate_abbreviations_table.py [output_header]

import sys
from pathlib import Path


def escape_cpp_string(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 0x20:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    return "".join(out)


def main():
    script_dir = Path(__file__).parent
    data_path = script_dir / "data" / "abbreviations.txt"
    default_out = (
        script_dir.parent.parent
        / "sherpa-onnx"
        / "csrc"
        / "offline-tts-zerotts-abbreviations-table.h"
    )
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_out

    entries = []  # (abbr, first_reading) -- first listed reading wins, per
                  # vi_normalizer.py's _expand_abbreviation()
    seen = set()
    skipped_lower = 0
    with open(data_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            abbr, readings = line.split(":", 1)
            if abbr != abbr.upper():
                skipped_lower += 1
                continue
            if abbr in seen:
                continue
            seen.add(abbr)
            first_reading = readings.split(",")[0]
            entries.append((abbr, first_reading))

    entries.sort(key=lambda e: e[0])

    lines = []
    for abbr, reading in entries:
        lines.append(
            f'    {{"{escape_cpp_string(abbr)}", "{escape_cpp_string(reading)}"}},'
        )

    header = f"""// sherpa-onnx/csrc/offline-tts-zerotts-abbreviations-table.h
//
// Auto-generated by scripts/zerotts/generate_abbreviations_table.py from
// scripts/zerotts/data/abbreviations.txt (adapted from soe-vinorm, MIT --
// see scripts/zerotts/data/LICENSE.soe-vinorm). Do not edit by hand.
//
// Uppercase-only entries (see the generator script's docstring for why the
// lowercase half of the source file is dropped): {len(entries)} entries,
// {skipped_lower} lowercase entries skipped.
//
// This table is only meant to be included from
// offline-tts-zerotts-vi-normalizer.cc.

#ifndef SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_ABBREVIATIONS_TABLE_H_
#define SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_ABBREVIATIONS_TABLE_H_

#include <cstdint>

namespace sherpa_onnx {{

struct ZeroTtsAbbreviationEntry {{
  const char *abbr;
  const char *reading;
}};

constexpr int32_t kZeroTtsAbbreviationsTableSize = {len(entries)};

static const ZeroTtsAbbreviationEntry kZeroTtsAbbreviationsTable[kZeroTtsAbbreviationsTableSize] = {{
{chr(10).join(lines)}
}};

}}  // namespace sherpa_onnx

#endif  // SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_ABBREVIATIONS_TABLE_H_
"""

    out_path.write_text(header, encoding="utf-8")
    print(f"Wrote {out_path} ({len(entries)} entries, {skipped_lower} lowercase skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
