#!/usr/bin/env python3
# Generate offline-tts-zerotts-letter-case-table.h -- Unicode uppercase/
# lowercase LETTER codepoint tables (general categories Lu / Ll) for the
# Vietnamese normalizer's abbreviation/acronym scanner, which needs to
# recognize runs of uppercase letters (Latin *and* Vietnamese, e.g. "Đ", "Ư",
# "Ạ".."Ỹ") the same way vi_normalizer.py's `_VN_UPPER`/`_VN_LOWER` character
# classes do, without hand-picking Unicode ranges.
#
# Usage:  python3 generate_letter_case_table.py [output_header]

import sys
import unicodedata
from pathlib import Path


def collect(category):
    return [cp for cp in range(0x10000) if unicodedata.category(chr(cp)) == category]


def format_array(values, per_line=9, indent="    "):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(f"0x{v:04X}" for v in values[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main():
    script_dir = Path(__file__).parent
    default_out = (
        script_dir.parent.parent
        / "sherpa-onnx"
        / "csrc"
        / "offline-tts-zerotts-letter-case-table.h"
    )
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_out

    upper = collect("Lu")
    lower = collect("Ll")
    unicode_version = unicodedata.unidata_version

    header = f"""// sherpa-onnx/csrc/offline-tts-zerotts-letter-case-table.h
//
// Auto-generated by scripts/zerotts/generate_letter_case_table.py
// from Python's unicodedata (Unicode {unicode_version}). Do not edit by hand.
//
// Unicode uppercase (Lu) / lowercase (Ll) letter codepoints, BMP only. Used
// by the Vietnamese normalizer's abbreviation scanner in place of
// vi_normalizer.py's hand-picked `_VN_UPPER`/`_VN_LOWER` character-class
// ranges -- a full Unicode category table is more robust than picking
// specific Vietnamese Unicode blocks by hand.
// This table is only meant to be included from
// offline-tts-zerotts-vi-normalizer.cc.

#ifndef SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_LETTER_CASE_TABLE_H_
#define SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_LETTER_CASE_TABLE_H_

#include <cstdint>

namespace sherpa_onnx {{

constexpr int32_t kUpperLetterTableSize = {len(upper)};
static const uint16_t kUpperLetterCodepoints[kUpperLetterTableSize] = {{
{format_array(upper)}
}};

constexpr int32_t kLowerLetterTableSize = {len(lower)};
static const uint16_t kLowerLetterCodepoints[kLowerLetterTableSize] = {{
{format_array(lower)}
}};

}}  // namespace sherpa_onnx

#endif  // SHERPA_ONNX_CSRC_OFFLINE_TTS_ZEROTTS_LETTER_CASE_TABLE_H_
"""

    out_path.write_text(header)
    print(f"Wrote {out_path} ({len(upper)} uppercase, {len(lower)} lowercase)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
